###========== SET UP
# LOAD LIBRARIES
```{r}
library(Seurat)
library(tidyverse)
library(patchwork)
source("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/Functions.R")
library(readr)
library(SeuratWrappers)

options(future.globals.maxSize = 100000 * 1024^10)
```

# SET UP DIRECTORIES
```{r}
setwd("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/04_CheckDbl_otherQC")
root_dir <- "/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/04_CheckDbl_otherQC"

RDSfiles <- paste0(root_dir, "/RDS_files")
dir.create(RDSfiles, showWarnings = F)

Figures_dir <- paste0(root_dir, "/Figures")
dir.create(Figures_dir, showWarnings = F)
```

# LISTS
```{r}
CanMarkers <- c(
  "SLC17A6", # glut cells,
  # "NR2E1", #adult NSCs
  # "SOX4", #neuronally committed precursors
  # "DCX", #migrating neuroblasts
  "GAD1", # gaba cells
  "PDGFRA", # OPCs
  "MBP", # Oligos
  "LRIG1", # Astro
  "CSF1R", # Microglia
  "FLT1" # Endothelial
)
```

###===== SCT PROCESS AND MERGE 
# subsetting w/out HVC_Pub3
```{r}
# prep
sub_SeuObj_byRegion <- readRDS(paste0(RDSfiles, "/IntegrateHarmony_20240819.rds"))
DefaultAssay(sub_SeuObj_byRegion) <- "RNA"
SeuObj_noHVCPub3 <- DietSeurat(sub_SeuObj_byRegion, assays = "RNA")
SeuObj_noHVCPub3 <- JoinLayers(SeuObj_noHVCPub3)
SeuObj_noHVCPub3 <- subset(SeuObj_noHVCPub3, subset = orig.ident == "HVC_Pub3", invert = T)

# standard process
assayUse <- "SCTjoin_regrID"
reductionUse <- paste0("pca_", assayUse)

# standard process
SeuObj_noHVCPub3 <- SCTransform(SeuObj_noHVCPub3,
  new.assay.name = assayUse,
  vars.to.regress = "BirdID", return.only.var.genes = T
)
SeuObj_noHVCPub3 <- RunPCA(SeuObj_noHVCPub3, assay = assayUse, reduction.name = reductionUse) %>%
  FindNeighbors(dims = 1:30, reduction = reductionUse) %>%
  FindClusters(resolution = 1, graph.name = paste0(assayUse, "_snn"), cluster.name = paste0("unintegrated_", reductionUse))
SeuObj_noHVCPub3 <- RunUMAP(SeuObj_noHVCPub3,
  dims = 1:30,
  reduction = reductionUse,
  reduction.name = paste0("umap.unintegrated_", assayUse)
)

saveRDS(SeuObj_noHVCPub3, file = paste0(RDSfiles, "/Merged_exlcHVCPub3_sctJoin_rgrsID_20240820.rds"))
```

# MERGED FIGURES
```{r}
# figures
sub_Fig_dir <- "/DblClean5_chckHVCpub3/ExlcHVCpub3/SctJoin"

DimPlot(SeuObj_noHVCPub3, reduction = paste0("umap.unintegrated_", assayUse), group.by = "RegionAcronym") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByRegion.tiff"),
  bg = "white", width = 9, height = 8
)

DimPlot(SeuObj_noHVCPub3, reduction = paste0("umap.unintegrated_", assayUse), cols = custom_colors, group.by = "orig.ident") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByOrigIdent.tiff"),
  bg = "white", width = 10, height = 8
)

DimPlot(SeuObj_noHVCPub3, reduction = paste0("umap.unintegrated_", assayUse), group.by = "CellClass_Sct_lvl2_CxG") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByCxGclass.tiff"),
  bg = "white", width = 9, height = 8
)

IDs <- unique(SeuObj_noHVCPub3$orig.ident)
Idents(SeuObj_noHVCPub3) <- "orig.ident"
plot_list <- list()
for (id in IDs) {
  p <- DimPlot(SeuObj_noHVCPub3, cells.highlight = CellsByIdentities(SeuObj_noHVCPub3, idents = id), order = id) + coord_equal()
  plot_list[[as.character(id)]] <- p
}
combined_plot <- wrap_plots(plot_list, ncol = 10)
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_HiglightByOrigIdent.tiff"), plot = combined_plot,
  bg = "white", width = 45, height = 20, dpi = 600
)
```


###--- other normalization
# sct by region
```{r}
# prep
DefaultAssay(SeuObj_noHVCPub3) <- "RNA"
SeuObj_noHVCPub3_2 <- DietSeurat(SeuObj_noHVCPub3, assays = "RNA")
SeuObj_noHVCPub3_2[["RNA"]] <- split(SeuObj_noHVCPub3_2[["RNA"]], f = SeuObj_noHVCPub3_2$RegionAcronym)

assayUse <- "SCTbyRegion_regrID"
reductionUse <- paste0("pca_", assayUse)

# standard process
SeuObj_noHVCPub3_2 <- SCTransform(SeuObj_noHVCPub3_2,
  new.assay.name = assayUse,
  vars.to.regress = "BirdID", return.only.var.genes = T
)
SeuObj_noHVCPub3_2 <- RunPCA(SeuObj_noHVCPub3_2, assay = assayUse, reduction.name = reductionUse) %>%
  FindNeighbors(dims = 1:30, reduction = reductionUse) %>%
  FindClusters(resolution = 1, graph.name = paste0(assayUse, "_snn"), cluster.name = paste0("unintegrated_", reductionUse))
SeuObj_noHVCPub3_2 <- RunUMAP(SeuObj_noHVCPub3_2,
  dims = 1:30,
  reduction = reductionUse,
  reduction.name = paste0("umap.unintegrated_", assayUse)
)

saveRDS(SeuObj_noHVCPub3_2, file = paste0(RDSfiles, "/Merged_exlcHVCPub3_sctByReg_rgrsID_20240820.rds"))
```

```{r}
# figures
sub_Fig_dir <- "/DblClean5_chckHVCpub3/ExlcHVCpub3/SctByRegion/"

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.unintegrated_", assayUse), group.by = "RegionAcronym") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByRegion.tiff"),
  bg = "white", width = 9, height = 8
)

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.unintegrated_", assayUse), cols = custom_colors, group.by = "orig.ident") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByOrigIdent.tiff"),
  bg = "white", width = 10, height = 8
)

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.unintegrated_", assayUse), group.by = "CellClass_Sct_lvl2_CxG") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByCxGclass.tiff"),
  bg = "white", width = 9, height = 8
)

IDs <- unique(SeuObj_noHVCPub3_2$orig.ident)
Idents(SeuObj_noHVCPub3_2) <- "orig.ident"
plot_list <- list()
for (id in IDs) {
  p <- DimPlot(SeuObj_noHVCPub3_2, cells.highlight = CellsByIdentities(SeuObj_noHVCPub3_2, idents = id), order = id) + coord_equal()
  plot_list[[as.character(id)]] <- p
}
combined_plot <- wrap_plots(plot_list, ncol = 10)
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_HiglightByOrigIdent.tiff"), plot = combined_plot,
  bg = "white", width = 45, height = 20, dpi = 600
)
```

###===== INTEGRATION
# rpca
```{r}
SeuObj_noHVCPub3_2 <- IntegrateLayers(
  object = SeuObj_noHVCPub3_2,
  method = RPCAIntegration,
  orig.reduction = "pca_SCTbyRegion_regrID",
  new.reduction = "integrated.rpca",
  normalization.method = "SCT",
  verbose = FALSE
)

# saveRDS(SeuObj_noHVCPub3_2, file = paste0(RDSfiles, "/IntegratedRPCA_exlcHVCPub3_sctByReg_rgrsID_20240820.rds"))
SeuObj_noHVCPub3_2 <- readRDS(file = paste0(RDSfiles, "/IntegratedRPCA_exlcHVCPub3_sctByReg_rgrsID_20240820.rds"))

assayUse <- "SCTbyRegion_regrID"
reductionUse <- "integrated.rpca"

SeuObj_noHVCPub3_2 <- FindNeighbors(SeuObj_noHVCPub3_2,
  dims = 1:30, reduction = reductionUse,
  graph.name = c("rpca_nn", "rpca_snn")
) %>%
  FindClusters(resolution = 1, graph.name = paste0("rpca", "_snn"), cluster.name = paste0(reductionUse, "_clusters"))
SeuObj_noHVCPub3_2 <- RunUMAP(SeuObj_noHVCPub3_2,
  dims = 1:30,
  reduction = reductionUse,
  reduction.name = paste0("umap.", reductionUse)
)

# save to label with umap location in CxG
# saveRDS(SeuObj_noHVCPub3_2, file = paste0(RDSfiles, "/IntegratedRPCA_exlcHVCPub3_sctByReg_rgrsID_20240821.rds"))
SeuObj_noHVCPub3_2 <- readRDS(file = paste0(RDSfiles, "/IntegratedRPCA_exlcHVCPub3_sctByReg_rgrsID_20240821.rds"))
```

# figures
```{r}
sub_Fig_dir <- "/DblClean5_chckHVCpub3/ExlcHVCpub3/SctByRegion_RPCA/"

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), group.by = "RegionAcronym") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByRegion.tiff"),
  bg = "white", width = 9, height = 8
)

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), cols = custom_colors, group.by = "orig.ident") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByOrigIdent.tiff"),
  bg = "white", width = 10, height = 8
)

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), group.by = "CellClass_Sct_lvl2_CxG") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByCxGclass.tiff"),
  bg = "white", width = 9, height = 8
)

IDs <- unique(SeuObj_noHVCPub3_2$orig.ident)
Idents(SeuObj_noHVCPub3_2) <- "orig.ident"
plot_list <- list()
for (id in IDs) {
  p <- DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), cells.highlight = CellsByIdentities(SeuObj_noHVCPub3_2, idents = id), order = id) + coord_equal()
  plot_list[[as.character(id)]] <- p
}
combined_plot <- wrap_plots(plot_list, ncol = 10)
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_HiglightByOrigIdent.tiff"), plot = combined_plot,
  bg = "white", width = 45, height = 20, dpi = 600
)


# DotPlots
Idents(SeuObj_noHVCPub3_2) <- "integrated.rpca_clusters"
SeuObj_noHVCPub3_2 <- BuildClusterTree(SeuObj_noHVCPub3_2, features = c(CanMarkers, "doublet_score"), reorder = T)
DotPlot(SeuObj_noHVCPub3_2, features = c(CanMarkers, "doublet_score"))
```

## add CxG hand labeling to further clean and subset
```{r}
assayUse <- "SCTbyRegion_regrID"
reductionUse <- "integrated.rpca"

# CxG labelling
CxG_cellLabels <- read_csv(paste0(root_dir, "/CellXGene/PallMerge-cell-labels-B6MBLT3H.csv"),
  skip = 2
) %>% as.data.frame()
rownames(CxG_cellLabels) <- CxG_cellLabels$index
CxG_cellLabels <- CxG_cellLabels %>% select(-index)

SeuObj_noHVCPub3_2 <- AddMetaData(SeuObj_noHVCPub3_2, metadata = CxG_cellLabels)
saveRDS(SeuObj_noHVCPub3_2, file = paste0(RDSfiles, "/IntegratedRPCA_CxGclass_20240826.rds"))

DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), group.by = "CxG_2") + coord_equal()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByCxG2class.tiff"),
  bg = "white", width = 9, height = 8
)

SeuObj_noHVCPub3_2@meta.data[["integrated.rpca_clusters"]] <- Idents(SeuObj_noHVCPub3_2)
DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), label = T, group.by = "integrated.rpca_clusters") + coord_equal() + NoLegend()
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_ByRPCAclusters.tiff"),
  bg = "white", width = 8, height = 8
)

Clusters <- unique(SeuObj_noHVCPub3_2$integrated.rpca_clusters)
Idents(SeuObj_noHVCPub3_2) <- "integrated.rpca_clusters"
plot_list <- list()
for (cluster in Clusters) {
  p <- DimPlot(SeuObj_noHVCPub3_2, reduction = paste0("umap.", reductionUse), cells.highlight = CellsByIdentities(SeuObj_noHVCPub3_2, idents = cluster), order = cluster) + coord_equal()
  plot_list[[as.character(cluster)]] <- p
}
combined_plot <- wrap_plots(plot_list, ncol = 10)
ggsave(
  filename = paste0(Figures_dir, sub_Fig_dir, "umap_HiglightByRPCAclusters.tiff"), plot = combined_plot,
  bg = "white", width = 45, height = 20, dpi = 600
)

# stacked plots
plotThis <- c("integrated.rpca_clusters", "orig.ident", "RegionAcronym", "CxG_2")
stackMeta <- FetchData(SeuObj_noHVCPub3_2, vars = plotThis)

stackedbarplot(stackMeta, "integrated.rpca_clusters", "CxG_2")
ggsave(
  filename = paste0(paste0(Figures_dir, sub_Fig_dir, "stackplot_ByCxG2class.tiff")),
  bg = "white", width = 10, height = 18
)

DotPlot(SeuObj_noHVCPub3_2, features = c(CanMarkers, "doublet_score")) + RotatedAxis()
ggsave(
  filename = paste0(paste0(Figures_dir, sub_Fig_dir, "dotplot_CanMarkers.tiff")),
  bg = "white", width = 6, height = 11
)
```
