---
title: "Doublet Finder"
output: html_notebook
---

# LOAD LIBRARIES
```{r}
library(tidyverse)
library(Seurat)
library(DoubletFinder)

```

# SET UP DIRECTORIES
```{r}
root_dir <- ("/project/Neuroinformatics_Core/Roberts_lab/s433904")

NFinput_Dir <- paste0(root_dir, "/PalliumEvo_AnalysisR/02_DoubletFinder_AllTele/CB_NF_inputData")
output_Dir <- paste0(root_dir, "/PalliumEvo_AnalysisR/02_DoubletFinder_AllTele/Output_CB_NF_DF")

```

# COPY OUTPUT NUCLUEAR FRACTION OUTPUT TO INPUT FOLDER
```{r}
# change
copyFrom_dir <- paste0(root_dir, '/PalliumEvo_AnalysisR/01_NuclearFraction_AllTele/Output_CB_NF')
UsePattern <- "CB_NF.RDS"
inputDir <- NFinput_Dir

# probably keep the same
input_list <- list.files(path = copyFrom_dir, pattern = UsePattern, recursive = TRUE)

for (x in input_list) {
if(!file.exists(paste(inputDir, basename(x), sep = "/"))){
  file.copy(from = paste(copyFrom_dir, x, sep = "/"),
  to = inputDir)
}else{
  print(sprintf("%s already has been copied", x))
}

}

```

#--- CREATE FOLDERS IN OUTPUT FOLDER FOR EACH SAMPLE
```{r}
NF_list <- 
list.files(
  path = NFinput_Dir,
  pattern = "_CB_NF.RDS"
)

folder_names <- NF_list %>%
str_extract("^([^_]+_[^_]+)")  # Regular expression to extract characters before the second underscore

walk(folder_names, ~dir.create(file.path(output_Dir, .x), showWarnings = F))

```


#--- RUN DOUBLET FINDER 

```{r}
for (a in folder_names) {
  print(a)
  #---
  # CREATE OUTPUT DIRECTORIES
  dir.create(file.path(file.path(output_Dir, a), "Figures"), showWarnings = F)
  figures_dir <- file.path(file.path(output_Dir, a), "Figures")
  
  dir.create(file.path(file.path(output_Dir, a), "RDS_files"), showWarnings = F)
  Rfiles_dir <- file.path(file.path(output_Dir, a), "RDS_files")
  
  dir.create(file.path(file.path(output_Dir, a), "Tables"), showWarnings = F)
  tables_dir <- file.path(file.path(output_Dir, a), "Tables")
  
  if (!file.exists(file.path(Rfiles_dir, sprintf("%s_onlySinglets.RDS", a)))){
    # LOAD DATA AND STD LOWER THRESHOLDING, AS PER DF BEST PRACTICES (TRY INCLUDE DOUBLETS)
    Obj_postNF <- readRDS(file.path(NFinput_Dir, sprintf("%s_CB_NF.RDS", a)))
  SeuObj <- subset(Obj_postNF, subset = nFeature_RNA > 100 & percent.mito < 5)
    
    #--- DOUBLET FINDER
    PCs = 30
    DFobj <- 
      SeuObj %>%
      SCTransform() %>% 
      RunPCA() %>% 
      RunUMAP(dims = 1:PCs)
    
    # pK IDENTIFICATION TO USE FOR DOUBLET.FINDER COMMAND 
    SweepRes <- paramSweep(DFobj, PCs = 1:PCs, sct = TRUE)
    SweepStats <- summarizeSweep(SweepRes, GT = FALSE)
    SweepResults <- find.pK(SweepStats)
    
    pk_toUse <- SweepResults %>% filter(BCmetric == max(BCmetric)) %>% select(pK)
    pk_toUse <- as.numeric(as.character((pk_toUse[1,1])))
    
    # Homotypic Doublet Proportion Estimate 
    homotypic.prop <- modelHomotypic(DFobj@active.ident)
    
    # USE FROM ORIGINAL CELL RECOVERY FOR DOUBLET CALCULATION
    Obj_preNF <- readRDS(paste0(copyFrom_dir, sprintf(
          "/%s/RDS_files/%s_SCTstdProcess.RDS", a, a)))
       
    # DOUBLET CALCULATION
    DoubletPercent <- 0.000008*ncol(Obj_preNF)
    
    nExp_poi <- round(DoubletPercent*ncol(Obj_preNF))  ## Assuming 0.0008% doublet formation rate/cell based on 10X
    nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
    
    # DOUBLET FINDER
    Obj_DF <- doubletFinder(DFobj, PCs = 1:PCs, pK = pk_toUse, nExp = nExp_poi, sct = TRUE)
    Obj_DF <- doubletFinder(Obj_DF, PCs = 1:PCs, pK = pk_toUse, nExp = nExp_poi.adj, reuse.pANN = colnames(Obj_DF@meta.data)[grepl("^pANN", colnames(Obj_DF@meta.data))], sct = TRUE)
    
  dfcols <- c(colnames(Obj_DF@meta.data)[grepl("^DF.classification", colnames(Obj_DF@meta.data))])
    
    seuMeta <- as.data.frame(Obj_DF@meta.data)
    seuFiltTemp <- seuMeta[seuMeta[,dfcols[[1]]] == "Singlet",]
    seuFilt <- seuFiltTemp[seuFiltTemp[,dfcols[[2]]] == "Singlet",]
    
    seuFilt$DoubletFinder <- rep("Singlets", nrow(seuFilt))
    
    df.meta <- seuFilt$DoubletFinder
    names(df.meta) <- row.names(seuFilt)
    
    Obj_DF$DoubletFinder <- df.meta
    Obj_DF$DoubletFinder[is.na(Obj_DF$DoubletFinder)] <- "Doublets"
    
    DFtable <- as.data.frame(table(Obj_DF$DoubletFinder))
    write.csv(DFtable, file = file.path(tables_dir, sprintf("%s_DoubletsCount.csv", a)), row.names = FALSE)
    
    # PLOTS
    DimPlot(Obj_DF, reduction = "umap", label = T) + coord_fixed(ratio = 1) + theme(legend.position="none")
    ggsave(file.path(figures_dir, sprintf("%s_%sPCs_UMAP.tiff", a, PCs)), width = 9, height = 6)
    
DimPlot(Obj_DF, reduction = "umap", group.by = "DoubletFinder") + coord_fixed(ratio = 1)
    ggsave(file.path(figures_dir, sprintf("%s_%sPCs_UMAP_doublets.tiff", a, PCs)), width = 9, height = 6)
    
    #--- SAVE OUTPUTS
    # SAVE FINAL OBJECT
    saveRDS(Obj_DF, file = (file.path(Rfiles_dir, sprintf("%s_labeledDoublets.RDS", a))))
    
    # SUBSET WITH ONLY SINGLETS 
    Obj_onlySinglet <- subset(Obj_DF, subset = DoubletFinder == "Singlets")
    saveRDS(Obj_onlySinglet, file = (file.path(Rfiles_dir, sprintf("%s_onlySinglets.RDS", a))))
    
    # Create a data frame with number of cells after each threshold
    column_counts <- data.frame(
      Sample = a,
      After_CB = ncol(Obj_preNF),
      After_CB_NF = ncol(Obj_postNF),
      After_CB_NF_100Feat5MitoThres = ncol(SeuObj),
      After_CB_NF_100Feat5MitoThres_DF = ncol(Obj_onlySinglet)
    )
    
    write.csv(column_counts, file = file.path(tables_dir, sprintf("%s_CellCountThroughQC_CBoutToDF.csv", a)), row.names = FALSE)
    
  } else{
    print(paste(a, "already had Doublet Finder run"))
  }
}

```


