---
title: "GABAergic song specific"
output: html_notebook
---

###========== SET UP
# LOAD LIBRARIES
```{r}
library(Seurat)
library(SeuratData)
library(tidyverse)
library(pheatmap)
library(scCustomize)
library(ggpubr)
library(readxl)
library(ggrastr)
library(scico)

source("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/Functions/CommonLevelsColors.R")
source("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/Functions/commonViz.R")
source("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/Functions/stackplots.R")
source("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/Functions/spearmanCorr_heatmap.R")

options(future.globals.maxSize = 100000 * 1024^10)
options(timeout = 100000)
```

# SET UP DIRECTORIES
```{r}
setwd("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_paper")
root_dir <- "/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_paper"

RDSfiles <- paste0(root_dir, "/RDS_files")
dir.create(RDSfiles, showWarnings = F)

Figures_dir <- paste0(root_dir, "/Figures")
dir.create(Figures_dir, showWarnings = F)

Tables_dir <- paste0(root_dir, "/Tables")
dir.create(Tables_dir, showWarnings = F)

PaperFigs <- "/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_paper/Figures/Fig4_GabaClass"
PaperFigs_supp <- "/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_paper/Figures/FigS4"
```

# LOADING DATSETS
```{r}
seuObj <- readRDS("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/06_Taxonomy/AllenClustering/RDS_files/OutputUse/seuObj_iterCluster_clean_20250131.rds")

seuObj$clusterName3 <- factor(seuObj$clusterName3, levels = dendro_order_3)
Idents(seuObj) <- "clusterName3"

GABA_Clust <- seuObj$clusterName3[grepl("LGE|MGE|CGE", seuObj$clusterName3)] %>% unique()
Gaba_seu <- subset(seuObj, subset = clusterName3 %in% GABA_Clust)
Gaba_seu <- ScaleData(Gaba_seu, assay = "SCTorigIdent3", features = rownames(Gaba_seu))

Gaba_seuAvg <- AverageExpression(object = Gaba_seu, assays = "SCTorigIdent3", layer = "data", group.by = c("clusterName3"), return.seurat = T)
```


#============== Exploratory ==========================================##########
# Transcription factors
```{r}
# GabaDEGs_roc <- FindAllMarkers(Gaba_seu,
#                                assay = "SCTorigIdent3",
#                                logfc.threshold = 1,
#                                min.pct = 0.05,
#                                only.pos = F,
#                                test.use = "roc"
#                                )
#
# # By TFs
# tf_list <- readxl::read_excel("/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/geneLists/tf_list.xlsx",
#   sheet = "Table S1. Related to Figure 1B",
#   skip = 1
# )
#
# colnames(tf_list)[colnames(tf_list) == "...4"] <- "isTF"
# TFs <- tf_list$Name[tf_list$isTF == "Yes"]
#
#
# TFs2Plot <- GabaDEGs_roc$gene[GabaDEGs_roc$gene %in% TFs] %>% unique()
# genes2Plot <- c(TFs2Plot, gabaMarkers[!gabaMarkers %in% TFs2Plot])
# clusteredByGenes <- Clustered_DotPlot(Gaba_seu, features = genes2Plot, cluster_ident = F, flip = T)
#
# # get clustered gene order
# col_order <- clusteredByGenes[[2]]@ht_list[["matrix_8"]]@column_order_list[[1]]
# clustered_gene_names <- colnames(clusteredByGenes[[2]]@ht_list[["matrix_8"]]@matrix)[col_order]
```



#============== Making figs ==========================================##########
##-- Can Markers and distribution (Panel A)
###-- Markers dot plot
```{r}
orderedGenes <- c(
  ## CGE
  "LAMP5", "TRPS1", # LAMP5 markers

  "MEF2C",
  "ETV1", "HMGA2",
  "LHX8", "SOX5", "THRB",
  "DPF3", "SP8", "PENK", "NR2E1", # SNCG/VIP
  "CNR1", "NR2F2",
  "ADARB2",

  ## MGE
  "SST", "NPY", "CHODL", "ALKAL1", # sst

  "PVALB", "ADSS1",
  "MAF", "NXPH1",
  "ST18", "NFIA", "PROX1", "RORA", "LHX6", "NFIB",
  "SOX6", "ZEB2", "ZNF536",
  "SETBP1", "SOX2",

  # LGE
  "FOXP1", "PBX3", "FOXP2", "MEIS2", "MEIS1", "ZFHX4", "TSHZ1"
)

gaba_CanMrks_dot <- DotPlot_scCustom(Gaba_seu,
  features = rev(orderedGenes),
  # col.min = 0, col.max = 3,
  dot.min = 0.01, dot.scale = 8,
  colors_use = colorRampPalette(c("#f0f0f0", "#020202"))(100)
) +
  theme(
    axis.line = element_line(color = "#060606"),
    axis.ticks = element_line(color = "#060606"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
  )


ggsave(
  filename = paste0(PaperFigs, "/dotplot_GabaCanMarkers_v2.svg"), plot = gaba_CanMrks_dot,
  width = 11, height = 4.5
)
```

###-- Region distribution stackplot
```{r}
Gaba_seu_meta <- FetchData(Gaba_seu, vars = c("orig.ident", "RegionAcronym", "clusterName3"))
Gaba_seu_meta$RegionAcronym <- factor(Gaba_seu_meta$RegionAcronym, levels = lvl_order)
Gaba_seu_meta$orig.ident <- factor(Gaba_seu_meta$orig.ident, levels = origIdent_lvls)

custom_colors <- c("#6F6F6F", "#7A5030FF", "#706543FF", "#1F593BFF", "#547B4FFF", "#6F97A8FF", "#486688FF", "#47477CFF", "#C8533AFF", "#D2BC6FFF")

stck <- stackedbarplot_colors(Gaba_seu_meta, "clusterName3", "RegionAcronym")
ggsave(
  filename = paste0(PaperFigs, "/stackplot_GABAcluster_byRgn.svg"), plot = stck,
  width = 10, height = 7
)


stck_supp <- stackedbarplot_colors(Gaba_seu_meta, "clusterName3", "orig.ident", custom_colors = origIdent_colors)
ggsave(
  filename = paste0(PaperFigs_supp, "/stackplot_GABAcluster_byOridIdent.svg"), plot = stck_supp,
  width = 15, height = 7
)
```

# Ratio and proportion plots
```{r}
allCells_meta <- FetchData(seuObj, vars = c("orig.ident", "RegionAcronym", "clusterName3", "Allen_classLvl2", "Allen_classLvl3"))
my_comparisons <- list(c("LMAN", "An"), c("RA", "Arco"), c("HVC", "NC"), c("HVC", "NCM"), c("NC", "NCM"))

#-- GABA to Gluts
allCells_meta_2 <- allCells_meta %>% filter(Allen_classLvl3 != "Neurogenic" & Allen_classLvl2 %in% c("Glutamatergic", "GABAergic"))
length(unique(allCells_meta_2$clusterName3))

allCells_meta_plot <- allCells_meta_2 %>%
  select(-clusterName3, -Allen_classLvl3) %>%
  count(orig.ident, RegionAcronym, Allen_classLvl2) %>%
  pivot_wider(names_from = Allen_classLvl2, values_from = n, values_fill = 0) %>%
  mutate(total = Glutamatergic + GABAergic) %>%
  mutate(GABAprop = GABAergic / total) %>%
  mutate(ratioGlut2Gaba = Glutamatergic / GABAergic)

allCells_meta_plot$RegionAcronym <- factor(allCells_meta_plot$RegionAcronym, levels = lvl_order)

gabaRatio <- ggboxplot(allCells_meta_plot,
  x = "RegionAcronym", y = "GABAprop", # can do GABAprop or ratioGlut2Gaba
  color = "RegionAcronym", palette = custom_colors,
  add = "jitter"
) +
  stat_compare_means(comparisons = my_comparisons, label = "p.signif", color = "#060606") +
  geom_hline(yintercept = mean(allCells_meta_plot$GABAprop), linetype = 2, color = "#060606") +
  stat_compare_means(
    label = "p.signif", method = "t.test",
    ref.group = ".all."
  )


#-- Specific GABA of interest
allCells_meta_3 <- allCells_meta %>% filter(Allen_classLvl3 != "Neurogenic" & Allen_classLvl2 == "GABAergic")
classes <- unique(allCells_meta_3$clusterName3)
plots_list <- list()

for (class in classes) {
  allCells_meta_plot2 <- allCells_meta_3 %>%
    select(-Allen_classLvl2, -Allen_classLvl3) %>%
    count(orig.ident, RegionAcronym, clusterName3) %>%
    pivot_wider(names_from = clusterName3, values_from = n, values_fill = 0) %>%
    mutate(total = rowSums(across(where(is.numeric)))) %>%
    mutate(ratioOfInterest = !!sym(class) / total)

  allCells_meta_plot2$RegionAcronym <- factor(allCells_meta_plot2$RegionAcronym, levels = lvl_order)

  plots_list[[paste(class, "plot", sep = "_")]] <- ggboxplot(allCells_meta_plot2,
    x = "RegionAcronym", y = "ratioOfInterest", # can do GABAprop or ratioGlut2Gaba
    color = "RegionAcronym", palette = custom_colors,
    add = "jitter",
    ylab = paste(class, ": GABA tot.")
  ) +
    stat_compare_means(comparisons = my_comparisons, label = "p.signif", color = "#060606") +
    geom_hline(yintercept = mean(allCells_meta_plot2$ratioOfInterest), linetype = 2, color = "#060606") +
    stat_compare_means(
      label = "p.signif", method = "t.test",
      ref.group = ".all."
    )

  # ggsave(filename = paste0(Figures_dir, "/PropPlots/", paste(class, "plot.tiff")), plot = plots_list[[paste(class, "plot")]],
  #        width = 11, height = 7)
}


# == Plot For Figure
GabaProps_ofInterest <- gabaRatio +
  plots_list[["MGE_PVALB(40)_plot"]] +
  plots_list[["MGE_song(33)_plot"]] +
  plots_list[["MGE_song(39)_plot"]] +
  plot_layout(guides = "collect", ncol = 1) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_line(color = "#060606"),
    axis.ticks.y = element_line(color = "#060606"),
    axis.line = element_line(color = "#060606")
  ) &
  NoLegend()

ggsave(
  filename = paste0(PaperFigs, "/boxplot_GABAcluster_PropsOfInterest.svg"), plot = GabaProps_ofInterest,
  width = 4, height = 8
)
```



# Heatmap using wilcox genes, since it is what I used in Astros
```{r}
re_run_mrks <- F
if (re_run_mrks == T) {
  gaba_degs_wilcox <- FindAllMarkers(Gaba_seu,
    assay = "SCTorigIdent3",
    logfc.threshold = 0.1,
    min.pct = 0.05,
    min.diff.pct = 0.15,
    only.pos = T,
    test.use = "wilcox",
    recorrect_umi = F
  ) %>% filter(p_val_adj < 0.05) # only one non-significant
  saveRDS(gaba_degs_wilcox,
    file = "/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/12_DGE/GABA/RDS_files/gaba_degs_wilcox_FC0.1pct0.05_pctDiff0.15_20260224.rds"
  )
  write_csv(gaba_degs_wilcox, file = paste0(Tables_dir, "/Fig4/GABAdegs_wilcox_20260224.csv"))
}

gaba_degs_wilcox <- readRDS(file = "/project/Neuroinformatics_Core/Roberts_lab/s433904/PalliumEvo_AnalysisR/12_DGE/GABA/RDS_files/gaba_degs_wilcox_FC0.1pct0.05_pctDiff0.15_20260224.rds")

cluster_stats <- Cluster_Stats_All_Samples(Gaba_seu, group_by_var = "RegionAcronym") %>% as.data.frame()

hMap_wlcx <- DoHeatmap(subset(Gaba_seu, downsample = 150), # smallest cluster has ~250
  features = gaba_degs_wilcox$gene,
  assay = "SCTorigIdent3",
  group.colors = c(
    "#a0acff", "#5552d5",
    sample(colorRampPalette(c("#c3f1fc", "#1f65b5"))(12)),
    sample(colorRampPalette(c("#76d8bb", "#529e9a"))(5))
  ),
  angle = 90, size = 2,
  raster = T
) +
  theme(
    axis.text.y  = element_blank(),
    axis.ticks.y = element_blank()
  )

ggsave(
  filename = paste0(PaperFigs_supp, "/heatmap_GABAcluster_WlcxMrks.tiff"), plot = hMap_wlcx,
  dpi = 300,
  width = 7, height = 7
)
```
